name: appodeal_helper
description: A new Flutter plugin project.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.15
  stack_appodeal_flutter: ^3.0.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  